### ISSUE TITLE
Add barplot 

### ISSUE THREAD

**Issue by tkrisztin** [iiasa/accelerator_service#20]
Could bar plots like the one below be added?

![Screenshot 2023-11-30 at 13 15 57](https://github.com/iiasa/accelerator_service/assets/9318979/401c836a-cfed-469f-b2b3-c681b9ed9679)

The x axis would be regions, the y axis could be % or absolute changes in a variable and the bars could be models.

**Comment by Wrufesh** [comment]
Fixed with recent release of scenario explorer with features like pivot, bar plot and stacked bar plot.
